import { ThemeProvider } from '@/components/ThemeProvider'
import '../globals.css'
import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import Bottombar from '@/components/Bottombar'
import { ClerkProvider, currentUser } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import PostButton from '@/components/Buttons/PostButton'
import LeftMenu from '@/components/LeftMenu'
import Rightbar from '@/components/Rightbar'
import { Suspense } from 'react'
import Loading from '@/components/Loading'
import { connectToDB } from '@/lib/mongoose'
import User from '@/lib/models/user'
import { redirect } from 'next/navigation'
import { Analytics } from '@vercel/analytics/next'

export const metadata: Metadata = {
  title: 'Twitter',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const connectDbPromise = connectToDB()
  const currentUserPromise = currentUser()
  const [db, currentUserData] = await Promise.all([connectDbPromise, currentUserPromise])
  if (!currentUserData) return null
  const userInfo = await User.findOne({ id: currentUserData.id }).select('onboarded')
  if (!userInfo) return redirect('/onboarding')
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang='en'>
        <body className={`${GeistSans.className} bg-black text-white`}>
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            enableSystem={false}
          >
            <div className='flex mx-auto max-w-2xl lg:max-w-5xl xl:max-w-6xl 2xl:max-w-7xl'>
              <div className='hidden xs:block'>
                <LeftMenu />
              </div>
              <div className='w-full min-h-screen max-w-[630px] xs:border xs:border-white/30'>
                <Suspense
                  fallback={<Loading className='items-center min-h-[90vh]' />}
                >
                  {children}
                  <Analytics />
                </Suspense>
                <div className='sm:hidden'>
                  <PostButton />
                </div>
                <div className='xs:hidden mt-24'>
                  <Bottombar />
                </div>
              </div>
              <div className='hidden lg:ml-8 lg:block'>
                <Rightbar />
              </div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
