import { ThemeProvider } from '@/components/ThemeProvider'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Bottombar from '@/components/Bottombar'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import PostButton from '@/components/Buttons/PostButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang='en'>
        <body className={`${inter.className} bg-black text-white`}>
          <ThemeProvider attribute='class' defaultTheme='dark' enableSystem={false}>
            {children}
            <PostButton />
            <div className='mt-24'>
              <Bottombar />
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
